//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizWPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnswerQuestionConnection
    {
        public int Id_AnswerQuestionConnection { get; set; }
        public int Id_Answer { get; set; }
        public int Id_Question { get; set; }
        public bool Is_Answer_Correct { get; set; }
    
        public virtual Answers Answers { get; set; }
        public virtual Questions Questions { get; set; }
    }
}
