//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizWPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stats
    {
        public int Id_Stat { get; set; }
        public string Player_Name { get; set; }
        public int Player_Points { get; set; }
        public System.DateTime Game_Played { get; set; }
    }
}
